FROM node:14-slim
RUN sed -i -E 's/http:\/\/deb.debian.org/http:\/\/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
RUN apt update && apt install -y git
RUN git clone https://github.com/MCSManager/Daemon /opt/docker-mcsm/dev/daemon
RUN cd /opt/docker-mcsm/dev/daemon && npm i --registry=https://registry.npmmirror.com
ENV TZ=Asia/Shanghai
WORKDIR /opt/docker-mcsm/dev/daemon
CMD npm run start