version: "3"
services:
    mcsm-mcsmanager-dev:
        container_name: mcsm-mcsmanager-dev
        build:
            context: .
            dockerfile: dockerfile-mcsmanager
            args:
                INSTALL_PATH: $INSTALL_PATH
        network_mode: "host"
        restart: always
        volumes:
            - $INSTALL_PATH/dev/mcsmanager/data:$INSTALL_PATH/dev/mcsmanager/data
            - $INSTALL_PATH/dev/mcsmanager/logs:$INSTALL_PATH/dev/mcsmanager/logs
            - $INSTALL_PATH/dev/daemon/data/Config:$INSTALL_PATH/dev/daemon/data/Config:ro
    mcsm-ui-dev:
        container_name: mcsm-ui-dev
        build:
            context: .
            dockerfile: dockerfile-ui
            args:
                INSTALL_PATH: $INSTALL_PATH
        network_mode: "host"
        restart: always
        volumes:
            - $INSTALL_PATH/dev/ui/data:$INSTALL_PATH/dev/ui/data
            - $INSTALL_PATH/dev/ui/logs:$INSTALL_PATH/dev/ui/logs
    mcsm-daemon-dev:
        container_name: mcsm-daemon-dev
        build:
            context: .
            dockerfile: dockerfile-daemon
            args:
                INSTALL_PATH: $INSTALL_PATH
        network_mode: "host"
        restart: always
        volumes:
            - $INSTALL_PATH/dev/daemon/data:$INSTALL_PATH/dev/daemon/data
            - $INSTALL_PATH/dev/daemon/logs:$INSTALL_PATH/dev/daemon/logs
            - /var/run/docker.sock:/var/run/docker.sock:ro