FROM node:14-slim
ARG INSTALL_PATH=/opt/docker-mcsm
ARG TZ=Asia/Shanghai
ENV TZ=${TZ}
RUN sed -i -E 's/http:\/\/deb.debian.org/http:\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt update && apt install -y git
RUN git clone --single-branch -b master --depth 1 https://github.com/MCSManager/MCSManager $INSTALL_PATH/dev/mcsmanager
RUN cd $INSTALL_PATH/dev/mcsmanager && mkdir public && npm i --registry=https://registry.npmmirror.com
WORKDIR $INSTALL_PATH/dev/mcsmanager
CMD npm run start