version: "3"
services:
    mcsm-mcsmanager-dev:
        container_name: mcsm-mcsmanager-dev
        build:
            context: .
            dockerfile: dockerfile-mcsmanager
        network_mode: "host"
        restart: always
        volumes:
            - "/opt/docker-mcsm/dev/mcsmanager/data:/opt/docker-mcsm/dev/mcsmanager/data"
            - "/opt/docker-mcsm/dev/mcsmanager/logs:/opt/docker-mcsm/dev/mcsmanager/logs"
            - "/opt/docker-mcsm/dev/daemon/data/Config:/opt/docker-mcsm/dev/daemon/data/Config:ro"
    mcsm-ui-dev:
        container_name: mcsm-ui-dev
        build:
            context: .
            dockerfile: dockerfile-ui
        network_mode: "host"
        restart: always
        volumes:
            - "/opt/docker-mcsm/dev/ui/data:/opt/docker-mcsm/dev/ui/data"
            - "/opt/docker-mcsm/dev/ui/logs:/opt/docker-mcsm/dev/ui/logs"
    mcsm-daemon-dev:
        container_name: mcsm-daemon-dev
        build:
            context: .
            dockerfile: dockerfile-daemon
        network_mode: "host"
        restart: always
        volumes:
            - "/opt/docker-mcsm/dev/daemon/data:/opt/docker-mcsm/dev/daemon/data"
            - "/opt/docker-mcsm/dev/daemon/logs:/opt/docker-mcsm/dev/daemon/logs"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"