FROM node:14-slim
ARG INSTALL_PATH=/opt/docker-mcsm
RUN sed -i -E 's/http:\/\/deb.debian.org/http:\/\/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt update && apt install -y git
RUN git clone --single-branch -b master --depth 1 https://github.com/MCSManager/Daemon $INSTALL_PATH/dev/daemon
RUN cd $INSTALL_PATH/dev/daemon && npm i --registry=https://registry.npmmirror.com
ENV TZ=Asia/Shanghai
WORKDIR $INSTALL_PATH/dev/daemon
CMD npm run start