version: "3"
services:
    mcsm-web:
        container_name: mcsm-web
        build:
            context: .
            dockerfile: dockerfile-web
        network_mode: "host"
        restart: always
        volumes:
            - "./web/data:/workspace/data"
            - "./web/logs:/workspace/logs"
            - "./daemon:/daemon:ro"
    mcsm-daemon:
        container_name: mcsm-daemon
        build:
            context: .
            dockerfile: dockerfile-daemon
        network_mode: "host"
        restart: always
        volumes:
            - "./daemon/data:/workspace/data"
            - "./daemon/logs:/workspace/logs"