version: "3"
services:
    mcsm-web:
        container_name: mcsm-web
        build:
            context: .
            dockerfile: dockerfile-web
        network_mode: "host"
        restart: always
        volumes:
            - "/opt/docker-mcsm/releases/web/data:/opt/docker-mcsm/releases/web/data"
            - "/opt/docker-mcsm/releases/web/logs:/opt/docker-mcsm/releases/web/logs"
            - "/opt/docker-mcsm/releases/daemon/data/Config:/opt/docker-mcsm/releases/daemon/data/Config:ro"
    mcsm-daemon:
        container_name: mcsm-daemon
        build:
            context: .
            dockerfile: dockerfile-daemon
        network_mode: "host"
        restart: always
        volumes:
            - "/opt/docker-mcsm/releases/daemon/data:/opt/docker-mcsm/releases/daemon/data"
            - "/opt/docker-mcsm/releases/daemon/logs:/opt/docker-mcsm/releases/daemon/logs"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"