version: "3"
services:
    mcsm-web:
        container_name: mcsm-web
        build:
            context: .
            dockerfile: dockerfile-web
            args:
                INSTALL_PATH: $INSTALL_PATH
        network_mode: "host"
        restart: always
        volumes:
            - $INSTALL_PATH/releases/web/data:$INSTALL_PATH/releases/web/data
            - $INSTALL_PATH/releases/web/logs:$INSTALL_PATH/releases/web/logs
            - $INSTALL_PATH/releases/daemon/data/Config:$INSTALL_PATH/releases/daemon/data/Config:ro
    mcsm-daemon:
        container_name: mcsm-daemon
        build:
            context: .
            dockerfile: dockerfile-daemon
            args:
                INSTALL_PATH: $INSTALL_PATH
        network_mode: "host"
        restart: always
        volumes:
            - $INSTALL_PATH/releases/daemon/data:$INSTALL_PATH/releases/daemon/data
            - $INSTALL_PATH/releases/daemon/logs:$INSTALL_PATH/releases/daemon/logs
            - /var/run/docker.sock:/var/run/docker.sock:ro