FROM node:14-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk --no-cache add git openssh
RUN git clone https://github.com/MCSManager/MCSManager-Web-Production /mnt/user/appdata/docker-mcsm/releases/web
RUN cd /mnt/user/appdata/docker-mcsm/releases/web && npm i --production --registry=https://registry.npmmirror.com
ENV TZ=Asia/Shanghai
WORKDIR /mnt/user/appdata/docker-mcsm/releases/web
CMD node app.js