version: "3"
services:
    mcsm-web:
        container_name: mcsm-web
        build:
            context: .
            dockerfile: dockerfile-web
        network_mode: "host"
        restart: always
        volumes:
            - "/mnt/user/appdata/docker-mcsm/releases/web/data:/mnt/user/appdata/docker-mcsm/releases/web/data"
            - "/mnt/user/appdata/docker-mcsm/releases/web/logs:/mnt/user/appdata/docker-mcsm/releases/web/logs"
            - "/mnt/user/appdata/docker-mcsm/releases/daemon/data/Config:/mnt/user/appdata/docker-mcsm/releases/daemon/data/Config:ro"
    mcsm-daemon:
        container_name: mcsm-daemon
        build:
            context: .
            dockerfile: dockerfile-daemon
        network_mode: "host"
        restart: always
        volumes:
            - "/mnt/user/appdata/docker-mcsm/releases/daemon/data:/mnt/user/appdata/docker-mcsm/releases/daemon/data"
            - "/mnt/user/appdata/docker-mcsm/releases/daemon/logs:/mnt/user/appdata/docker-mcsm/releases/daemon/logs"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"